#
# AgriDocs ReadTheDocs configuration.
#

# Site Title
site_name: AgriCraft Documentation

# Page Index
pages:
  - Home: 'index.md'
  - Terminology: 'terminology.md'
  - AgriJSON:
    - About: 'agri_json.md'
    - AgriPlant: 'agri_plant.md'
    - AgriWeed: 'agri_weed.md'
    - AgriMutation: 'agri_mutation.md'
    - AgriSoil: 'agri_soil.md'
    - AgriFertilizer: 'agri_fertilizer.md'
  - FAQ: 'faq.md'
  - Roadmap: 'roadmap.md'
  - Known Issues: 'known_issues.md'
