#
# AgriDocs ReadTheDocs configuration.
#

# Site Configuration
site_name: AgriCraft Documentation
site_url: https://agridocs.readthedocs.io
repo_url: https://github.com/AgriCraft/AgriDocs/

theme:
  name: readthedocs

# Page Index
nav:
  - Home: 'index.md'
  - Terminology: 'terminology.md'
  - AgriJSON:
    - About: 'agri_json.md'
    - AgriPlant: 'agri_plant.md'
    - AgriWeed: 'agri_weed.md'
    - AgriMutation: 'agri_mutation.md'
    - AgriSoil: 'agri_soil.md'
    - AgriFertilizer: 'agri_fertilizer.md'
  - FAQ: 'faq.md'
  - Roadmap: 'roadmap.md'
  - Known Issues: 'known_issues.md'
